# Generated by Django 4.2 on 2023-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='execution_datetime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_notification',
        ),
        migrations.AddField(
            model_name='task',
            name='execution_day',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='task',
            name='execution_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
